project:
  type: book
  execute-dir: project

book:
  title: "Numerical Methods for Quantum Optics and Open Quantum Systems"
  author:
    - name: Alberto Mercurio
      orcid: 0000-0001-7814-1936
      email: alberto.mercurio@epfl.ch
      affiliations:
        - id: 1
          name: École Polytechnique Fédérale de Lausanne (EPFL)
          address: Rte Cantonale
          city: Lausanne
          state: Switzerland
          postal-code: 1015
    - name: Daniele De Bernardis
      orcid: 0000-0002-9618-0389
      email: daniele.debernardis@cnr.it
      affiliations:
        - id: 2
          name: Istituto Nazionale di Ottica (INO-CNR)
          address: Largo Enrico Fermi, 6
          city: Firenze
          state: Italia
          postal-code: 50125
  date: today
  date-format: "DD-MM-YYYY"
  downloads: [pdf]
  navbar:
    search: true
    tools:
      - icon: github
        href:  https://github.com/Daniele-PyBECTN/Computational_quantum_optics_lectures
  chapters:
    - index.qmd
    # - lecture1/ # Introduction to Quantum Systems. The concept of matrices
    - lecture1/introduction.qmd # Introduction to Python
    - lecture1/linear_algebra.qmd
    - lecture1/numba_and_jax.qmd
    - lecture1/ordinary_differential_equations.qmd
    # - lecture1/ # Representation of Quantum Operators in Numpy
    # - lecture1/ # Closed Quantum Systems - Schrodinger Equation
    # - lecture1/ # Closed Quantum Systems in QuTiP
    # - lecture2/ # Open Quantum Systems - Lindblad Equation
    # - lecture2/ # Open Quantum Systems in QuTiP
    # - lecture3/ # Quantum Observables and Correlation Functions
    # - lecture3/ # Quantum Observables and Correlation Functions in QuTiP
    # - lecture3/ # Applications on several systems (trapped ion, optomechanics, etc.)
    # - lecture4/ # Quantum Monte Carlo - Quantum Trajectories
    # - lecture4/ # Quantum Monte Carlo in QuTiP
    - bibliography.qmd
  appendices: 
    - appendices/quantum-harmonic-oscillator.qmd

number-depth: 3
bibliography: bibliography.bib

# default format for all files
format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: atom-one
    css: styles.css
    toc: true
    published-title: Last Update
    date-format: iso
    code-line-numbers: true
    colorlinks: true
    footnotes-hover: true
    fig-responsive: true
    fig-align: center
    fig-width: 5
    fig-height: 2.5
    fig-dpi: 160
  pdf:
    documentclass: scrreprt
    toc: true
    # keep-tex: true
    margin-left: 1.2in
    margin-right: 1.2in
    margin-top: 1.2in
    margin-bottom: 1.8in
    link-citations: true
    fig-align: center
    fig-width: 7
    fig-height: 3.5
    template-partials:
      - partials/title.tex    # our custom title block
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}   % author–affiliation macros
        \usepackage{orcidlink}
        \usepackage{hyperref}            % clickable e-mails
        \usepackage{physics}
        \renewcommand\Authfont{\Large}
        \renewcommand\Affilfont{\small}

jupyter: python3

execute:
  eval: true
  cache: false
  freeze: false