name: Build container image

permissions:
  contents: read        # still let the workflow read the repo
  packages: write       # <-- this is the missing bit

on:
  push:
    branches:
      - notebooks

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with: 
        DOCKER_USERNAME: ${{github.actor}}
        DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        BINDER_CACHE: true
        DOCKER_REGISTRY: "ghcr.io"
        IMAGE_NAME: "daniele-pybectn/comp-qoptics-binder"